# https://cloud.google.com/appengine/docs/standard/python/config/appref

# application: bridgy-federated
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: 1h

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest
- name: pycrypto
  version: latest
- name: ssl
  version: latest
- name: webob
  version: latest

handlers:

# static
- url: /(static/bootstrap.*\.css)
  static_files: local/lib/python2.7/site-packages/oauth_dropins/\1
  upload: local/lib/python2.7/site-packages/oauth_dropins/static/bootstrap.*\.css

- url: /static
  static_dir: static

- url: /oauth_dropins/static
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/static

- url: /.well-known
  static_dir: .well-known

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: 1m

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# dynamic
- url: /wm/.+
  script: add_webmention.app
  secure: always

- url: /webmention
  script: webmention.app
  secure: always

- url: /[^@/]+/?(inbox)?
  script: activitypub.app
  secure: always

- url: /(acct:)?@[^/]+/?
  script: webfinger.app
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\.git.*
- ^(.*/)?.*\.bak$
- ^(.*/)?(\.?coverage|debian|docs?|examples?|l|pydocs?|python3|ref|samples?|TAGS|tests?)/.*
- ^local/lib/python2.7/site-packages/setuptools/script\ \(dev\)\.tmpl$
